# Generated by Django 6.0.3 on 2026-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('date_creation', models.DateField()),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
